export const ENGLISH_COPY = {
  changesLeft: 'CHANGES LEFT',
  errors: 'ERRORS',
  reportCorrect: 'CHANGE FOUND',
  reportIncorrect: 'NOT A CHANGE',
  searchTimeout: "TIME'S UP",
  gameOver: 'YOU WERE ERASED',
  missedAnomaly: 'MISSED ANOMALY',
  anomalyRevealHint: 'OUTLINED IN RED IN THE ROOM',
  roomReached: 'ROOM REACHED',
  finalTime: 'FINAL TIME',
  tryAgain: 'REBUILD THE LOOP',
  rewardedContinue: 'WATCH AD - +1 LIFE',
  rewardedAdLoading: 'LOADING VIDEO...',
  rewardedAdUnavailable: 'NO VIDEO AVAILABLE - USE TRY AGAIN',
  victory: 'YOU GOT OUT',
  activeTime: 'ACTIVE TIME',
  penalties: 'PENALTIES',
  perfectRun: 'PERFECT RUN',
  playAgain: 'PLAY AGAIN',
  modeSelect: 'MODE SELECT',
} as const;
