import type { StoryInteractionDefinition } from '../../gameplay/story/StoryInteraction';

export const BEDROOM_FAMILY_PHOTO_OBJECT_ID = 'bedroom-family-photo';
export const BEDROOM_STORY_OBJECT_IDS = {
  photo: BEDROOM_FAMILY_PHOTO_OBJECT_ID,
  radio: 'bedroom-radio',
  television: 'bedroom-television',
  wardrobe: 'bedroom-wardrobe',
  bed: 'bedroom-bed',
  books: 'bedroom-books',
  picture: 'bedroom-wall-picture',
  plant: 'bedroom-plant',
} as const;
export const BATHROOM_STORY_OBJECT_IDS = {
  mirror: 'bathroom-mirror',
  bathtub: 'bathroom-bathtub',
  vanity: 'bathroom-vanity',
  toothbrushes: 'bathroom-toothbrushes',
  duck: 'bathroom-rubber-duck',
  candle: 'bathroom-candle',
  towels: 'bathroom-towels',
} as const;
export const CORRIDOR_PHONE_OBJECT_ID = 'corridor-phone';
export const OFFICE_STORY_OBJECT_IDS = {
  radio: 'office-radio',
  phone: 'office-phone',
  clock: 'office-wall-clock',
  photo: 'office-desk-photo',
} as const;
export const KITCHEN_STORY_OBJECT_IDS = {
  fridge: 'kitchen-fridge',
  microwave: 'kitchen-microwave',
  sink: 'kitchen-sink',
  stove: 'kitchen-stove',
  coffeeMachine: 'kitchen-coffee-machine',
  trashcan: 'kitchen-trashcan',
  breakfastTable: 'kitchen-breakfast-table',
} as const;

export const STORY_DISAPPEARANCE_PROTECTED_TARGET_IDS_BY_ROOM = {
  'greybox-bedroom': ['radio', 'photo-frame'],
  bathroom: ['mirror'],
  office: ['desk-photo'],
  kitchen: ['breakfast-table'],
} as const satisfies Readonly<Record<string, readonly string[]>>;

export const STORY_INTERACTION_CATALOG = [
  {
    id: BEDROOM_FAMILY_PHOTO_OBJECT_ID,
    roomId: 'greybox-bedroom',
    targetId: 'photo-frame',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
    requiredEventIdBeforeExit: 'bedroom-empty-place',
    exitInstruction: 'EXAMINE THE FAMILY PHOTO',
  },
  {
    id: BEDROOM_STORY_OBJECT_IDS.radio,
    roomId: 'greybox-bedroom',
    targetId: 'radio',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BEDROOM_STORY_OBJECT_IDS.television,
    roomId: 'greybox-bedroom',
    targetId: 'television',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BEDROOM_STORY_OBJECT_IDS.wardrobe,
    roomId: 'greybox-bedroom',
    targetId: 'wardrobe',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BEDROOM_STORY_OBJECT_IDS.bed,
    roomId: 'greybox-bedroom',
    targetId: 'bed',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BEDROOM_STORY_OBJECT_IDS.books,
    roomId: 'greybox-bedroom',
    targetId: 'books',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BEDROOM_STORY_OBJECT_IDS.picture,
    roomId: 'greybox-bedroom',
    targetId: 'picture',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BEDROOM_STORY_OBJECT_IDS.plant,
    roomId: 'greybox-bedroom',
    targetId: 'plant',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BATHROOM_STORY_OBJECT_IDS.mirror,
    roomId: 'bathroom',
    targetId: 'mirror',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
    requiredEventIdBeforeExit: 'bathroom-mirror-inspection',
    exitInstruction: 'EXAMINE THE MIRROR',
  },
  {
    id: BATHROOM_STORY_OBJECT_IDS.bathtub,
    roomId: 'bathroom',
    targetId: 'bathtub',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BATHROOM_STORY_OBJECT_IDS.vanity,
    roomId: 'bathroom',
    targetId: 'vanity',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BATHROOM_STORY_OBJECT_IDS.toothbrushes,
    roomId: 'bathroom',
    targetId: 'toothbrush-cup',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BATHROOM_STORY_OBJECT_IDS.duck,
    roomId: 'bathroom',
    targetId: 'rubber-duck',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BATHROOM_STORY_OBJECT_IDS.candle,
    roomId: 'bathroom',
    targetId: 'candle',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: BATHROOM_STORY_OBJECT_IDS.towels,
    roomId: 'bathroom',
    targetId: 'towels-stacked',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: CORRIDOR_PHONE_OBJECT_ID,
    roomId: 'first-corridor',
    targetId: 'phone',
    actionLabel: 'ANSWER',
    phases: ['room-complete'],
  },
  {
    id: OFFICE_STORY_OBJECT_IDS.radio,
    roomId: 'office',
    targetId: 'radio',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: OFFICE_STORY_OBJECT_IDS.phone,
    roomId: 'office',
    targetId: 'office-phone',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: OFFICE_STORY_OBJECT_IDS.clock,
    roomId: 'office',
    targetId: 'wall-clock',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: OFFICE_STORY_OBJECT_IDS.photo,
    roomId: 'office',
    targetId: 'desk-photo',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
    requiredEventIdBeforeExit: 'office-erased-name-inspection',
    exitInstruction: 'EXAMINE THE DESK PHOTO',
  },
  {
    id: KITCHEN_STORY_OBJECT_IDS.fridge,
    roomId: 'kitchen',
    targetId: 'fridge',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: KITCHEN_STORY_OBJECT_IDS.microwave,
    roomId: 'kitchen',
    targetId: 'microwave',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: KITCHEN_STORY_OBJECT_IDS.sink,
    roomId: 'kitchen',
    targetId: 'sink',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: KITCHEN_STORY_OBJECT_IDS.stove,
    roomId: 'kitchen',
    targetId: 'stove',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: KITCHEN_STORY_OBJECT_IDS.coffeeMachine,
    roomId: 'kitchen',
    targetId: 'coffee-machine',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: KITCHEN_STORY_OBJECT_IDS.trashcan,
    roomId: 'kitchen',
    targetId: 'trashcan',
    actionLabel: 'EXAMINE',
    phases: ['room-complete'],
  },
  {
    id: KITCHEN_STORY_OBJECT_IDS.breakfastTable,
    roomId: 'kitchen',
    targetId: 'breakfast-table',
    actionLabel: 'COUNT',
    phases: ['room-complete'],
    requiredEventIdBeforeExit: 'kitchen-fourth-place-inspection',
    exitInstruction: 'COUNT THE PLACES',
  },
] as const satisfies readonly StoryInteractionDefinition[];
