import {
  FinalRouteRoomBase,
  type FinalRouteRoomConfig,
} from './FinalRouteRoomBase';

const CONFIG: FinalRouteRoomConfig = {
  id: 'main-hall',
  displayName: 'Main Hall',
  prefix: 'MainHall',
  halfWidth: 4.6,
  halfDepth: 4.2,
  roomHeight: 3.6,
  entranceX: -3,
  exitWall: 'north',
  exitCenter: 0,
  observationDurationMs: 10_000,
  searchDurationMs: 25_000,
  anomalyCount: { min: 3, max: 4 },
  playerSpawn: [-3, 0, 3.45],
  floorStyle: 'wood',
  props: [
    {
      id: 'archive-core',
      name: 'ANOM_MainHall_ArchiveCore',
      position: [0, 0, 0.45],
      size: [1.25, 1.55, 1.25],
      color: '#596c69',
      shape: 'orb',
      anomalyStyle: 'story',
      collision: true,
      detail: 'rings',
    },
    {
      id: 'choice-escape',
      name: 'ANOM_MainHall_ChoiceEscape',
      position: [-2.45, 0, -1.55],
      size: [0.8, 1.05, 0.8],
      color: '#657c76',
      shape: 'cylinder',
      anomalyStyle: 'choice',
      collision: true,
      detail: 'labels',
    },
    {
      id: 'choice-remember',
      name: 'ANOM_MainHall_ChoiceRemember',
      position: [0, 0, -1.85],
      size: [0.8, 1.05, 0.8],
      color: '#9a7954',
      shape: 'cylinder',
      anomalyStyle: 'choice',
      collision: true,
      detail: 'labels',
    },
    {
      id: 'choice-replaced',
      name: 'ANOM_MainHall_ChoiceReplaced',
      position: [2.45, 0, -1.55],
      size: [0.8, 1.05, 0.8],
      color: '#79565f',
      shape: 'cylinder',
      anomalyStyle: 'choice',
      collision: true,
      detail: 'labels',
    },
    {
      id: 'west-archive',
      name: 'ANOM_MainHall_WestArchive',
      position: [-4.05, 0, -1.8],
      size: [0.65, 2.25, 2.4],
      color: '#55483f',
      anomalyStyle: 'standard',
      collision: true,
      detail: 'records',
    },
    {
      id: 'east-archive',
      name: 'ANOM_MainHall_EastArchive',
      position: [4.05, 0, -1.8],
      size: [0.65, 2.25, 2.4],
      color: '#55483f',
      anomalyStyle: 'standard',
      collision: true,
      detail: 'records',
    },
    {
      id: 'family-register',
      name: 'ANOM_MainHall_FamilyRegister',
      position: [3.55, 0, 2.5],
      size: [1.45, 0.82, 0.65],
      color: '#625044',
      anomalyStyle: 'standard',
      collision: true,
      detail: 'records',
    },
    {
      id: 'hall-bench',
      name: 'ANOM_MainHall_HallBench',
      position: [-3.6, 0, 2.15],
      size: [1.55, 0.66, 0.62],
      color: '#735e51',
      anomalyStyle: 'standard',
      collision: true,
    },
    {
      id: 'memory-portrait',
      name: 'ANOM_MainHall_MemoryPortrait',
      position: [-1.65, 0, -3.95],
      size: [1.15, 1.55, 0.12],
      color: '#765a44',
      shape: 'frame',
      anomalyStyle: 'standard',
    },
    {
      id: 'deletion-portrait',
      name: 'ANOM_MainHall_DeletionPortrait',
      position: [1.65, 0, -3.95],
      size: [1.15, 1.55, 0.12],
      color: '#5c4743',
      shape: 'frame',
      anomalyStyle: 'standard',
    },
    {
      id: 'central-rug',
      name: 'ANOM_MainHall_CentralRug',
      position: [0, 0.02, 1.8],
      size: [3.3, 0.05, 2.25],
      color: '#624648',
      anomalyStyle: 'standard',
    },
    {
      id: 'archive-clock',
      name: 'ANOM_MainHall_ArchiveClock',
      position: [3.9, 0, 0.75],
      size: [0.55, 1.75, 0.42],
      color: '#67513f',
      anomalyStyle: 'standard',
      detail: 'screen',
    },
  ],
};

export class GreyboxMainHall extends FinalRouteRoomBase {
  public constructor() {
    super(CONFIG);
  }

  protected createRoomDetails(): void {
    this.getVisualRoot().add(
      this.createDetailBox('DETAIL_MainHall_EscapeLabel', [1.1, 0.12, 0.32], [-2.45, 1.1, -1.55], '#78958c'),
      this.createDetailBox('DETAIL_MainHall_RememberLabel', [1.1, 0.12, 0.32], [0, 1.1, -1.85], '#b08a5c'),
      this.createDetailBox('DETAIL_MainHall_ReplacedLabel', [1.1, 0.12, 0.32], [2.45, 1.1, -1.55], '#875e68'),
      this.createDetailBox('DETAIL_MainHall_ArchiveBeam', [0.08, 2.1, 0.08], [0, 2.45, 0.45], '#7ba49a'),
    );
  }
}
